# -*- coding: utf-8 -*-
"""resnet18 (transfer learning).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11AeDLy6ldYIkBlDdaeoz-_GHf-ulL9I2
"""

import os
import copy
import zipfile
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms, models

from torch.utils.data import DataLoader, random_split

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

SEED = 42

torch.manual_seed(SEED)
np.random.seed(SEED)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(device)

from google.colab import files

files.upload()

!mkdir ~/.kaggle

!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

!unzip -q chest-xray-pneumonia.zip

print(os.listdir('/content/chest_xray'))

train_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.RandomAffine(
        degrees=0,
        translate=(0.05,0.05)
    ),
    transforms.ToTensor()
])

test_transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

train_dataset = datasets.ImageFolder(
    root='/content/chest_xray/train',
    transform=train_transform
)

val_dataset = datasets.ImageFolder(
    root='/content/chest_xray/train',
    transform=test_transform
)

test_dataset = datasets.ImageFolder(
    root='/content/chest_xray/test',
    transform=test_transform
)

print(train_dataset.classes)

#Divisão Treino e Validação

from sklearn.model_selection import train_test_split
from torch.utils.data import Subset

indices = list(range(len(train_dataset)))

train_indices, val_indices = train_test_split(
    indices,
    test_size=0.2,
    random_state=SEED,
    stratify=train_dataset.targets
)

train_dataset = Subset(
    train_dataset,
    train_indices
)

val_dataset = Subset(
    val_dataset,
    val_indices
)

#DataLoaders

BATCH_SIZE = 64

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

# Arquitetura ResNet18 pré-treinada

model = models.resnet18(
    weights=models.ResNet18_Weights.IMAGENET1K_V1
)

# Congelar todas as camadas
for param in model.parameters():
    param.requires_grad = False

# Substituir a última camada
num_features = model.fc.in_features

model.fc = nn.Sequential(

    nn.Linear(num_features, 128),

    nn.ReLU(),

    nn.Dropout(0.5),

    nn.Linear(128, 2)

)

model = model.to(device)

#Função de Perda

criterion = nn.CrossEntropyLoss()

#Otimizador - ADAM

optimizer = optim.Adam(
    model.fc.parameters(),
    lr=0.001
)

#Épocas

NUM_EPOCHS = 30

from google.colab import drive

drive.mount('/content/drive')

import os

SAVE_DIR = "/content/drive/MyDrive/pneumonia/Experimento_3"

os.makedirs(SAVE_DIR, exist_ok=True)

import copy

best_val_loss = float('inf')
patience = 10
counter = 0

best_model_wts = copy.deepcopy(model.state_dict())

start_epoch = 0
start_epoch = 0

#Armazenar as métricas nas variáveis

train_losses = []
val_losses = []

train_accs = []
val_accs = []

checkpoint_path = os.path.join(SAVE_DIR, "checkpoint.pth")

if os.path.exists(checkpoint_path):

    checkpoint = torch.load(
        checkpoint_path,
        map_location=device
    )

    #Salvando o Histórico
    train_losses = checkpoint.get('train_losses', [])
    val_losses = checkpoint.get('val_losses', [])

    train_accs = checkpoint.get('train_accs', [])
    val_accs = checkpoint.get('val_accs', [])

    model.load_state_dict(
    checkpoint['model_state_dict']
    )



    optimizer.load_state_dict(
        checkpoint['optimizer_state_dict']
    )

    start_epoch = checkpoint['epoch'] + 1

    best_val_loss = checkpoint['best_val_loss']

    print(f"Treinamento retomado da época {start_epoch}")

else:

    print("Iniciando treinamento do zero")

print("Treino:", len(train_dataset))
print("Validação:", len(val_dataset))
print("Teste:", len(test_dataset))

print(len(train_loader))
print(len(val_loader))

# TREINAMENTO

NUM_EPOCHS = 30

for epoch in range(start_epoch, NUM_EPOCHS):





    model.train()

    running_loss = 0
    correct = 0
    total = 0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

        _, predicted = outputs.max(1)

        total += labels.size(0)

        correct += predicted.eq(labels).sum().item()

    train_loss = running_loss / len(train_loader)
    train_acc = correct / total

    train_losses.append(train_loss)
    train_accs.append(train_acc)

    #############################
    # VALIDAÇÃO
    #############################

    model.eval()

    running_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in val_loader:

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)

            loss = criterion(outputs, labels)

            running_loss += loss.item()

            _, predicted = outputs.max(1)

            total += labels.size(0)

            correct += predicted.eq(labels).sum().item()

    val_loss = running_loss / len(val_loader)
    val_acc = correct / total

    val_losses.append(val_loss)
    val_accs.append(val_acc)

    print(
        f'Epoch [{epoch+1}/{NUM_EPOCHS}] | '
        f'Train Loss={train_loss:.10f} | '
        f'Val Loss={val_loss:.10f} | '
        f'Train Acc={train_acc:.10f} | '
        f'Val Acc={val_acc:.10f}'
    )

    ###################################
    # SALVAR CHECKPOINT
    ###################################

    checkpoint = {

    'epoch': epoch,

    'model_state_dict': model.state_dict(),

    'optimizer_state_dict': optimizer.state_dict(),

    'best_val_loss': best_val_loss,

    'train_losses': train_losses,

    'val_losses': val_losses,

    'train_accs': train_accs,

    'val_accs': val_accs

}


    torch.save(
        checkpoint,
        os.path.join(
            SAVE_DIR,
            "checkpoint.pth"
        )
    )

    ###################################
    # MELHOR MODELO
    ###################################

    if val_loss < best_val_loss:

      best_val_loss = val_loss

      best_model_wts = copy.deepcopy(
          model.state_dict()
      )

      torch.save(
          model.state_dict(),
          os.path.join(
              SAVE_DIR,
              "best_model.pth"
          )
      )

      counter = 0

      print(
          f"Melhor modelo salvo! "
          f"Val Loss = {val_loss:.4f}"
      )

    else:

        counter += 1

        print(
            f"Sem melhora ({counter}/{patience})"
        )

        if counter >= patience:

            print("Early Stopping")

            break

#Restaurando o melhor modelo
model = models.resnet18(
    weights=None
)

num_features = model.fc.in_features

model.fc = nn.Sequential(

    nn.Linear(num_features,128),

    nn.ReLU(),

    nn.Dropout(0.5),

    nn.Linear(128,2)

)

model = model.to(device)

model.load_state_dict(
    torch.load(
        os.path.join(
            SAVE_DIR,
            "best_model.pth"
        ),
        map_location=device
    )
)

model.eval()

#Avalindo o conjunto de testes

model.eval()

y_true = []
y_pred = []

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)

        outputs = model(images)

        _, predicted = outputs.max(1)

        y_true.extend(labels.numpy())
        y_pred.extend(predicted.cpu().numpy())

acc = accuracy_score(y_true,y_pred)
precision = precision_score(y_true,y_pred)
recall = recall_score(y_true,y_pred)
f1 = f1_score(y_true,y_pred)

print("Accuracy :",acc)
print("Precision:",precision)
print("Recall   :",recall)
print("F1-score :",f1)

with open("/content/drive/MyDrive/pneumonia/Experimento_3/metricas_BaseLine.txt", "w") as f:

    f.write(f"Accuracy : {acc:.6f}\n")
    f.write(f"Precision: {precision:.6f}\n")
    f.write(f"Recall   : {recall:.6f}\n")
    f.write(f"F1-score : {f1:.6f}\n")

print("Métricas salvas em metricas.txt")

import pandas as pd

resultados = pd.DataFrame({

    "Modelo": ["CNN Baseline"],

    "Accuracy": [acc],

    "Precision": [precision],

    "Recall": [recall],

    "F1-score": [f1]

})

resultados.to_csv(
    os.path.join(SAVE_DIR, "metricas.csv"),
    index=False
)

print("Métricas salvas em metricas.csv")

report = classification_report(
    y_true,
    y_pred,
    target_names=['NORMAL', 'PNEUMONIA']
)

print(report)

with open(
    "/content/drive/MyDrive/pneumonia/Experimento_3/classification_report_BaseLine.txt",
    "w"
) as f:

    f.write("CNN Baseline\n")
    f.write("="*60 + "\n\n")

    f.write(f"Accuracy : {acc:.6f}\n")
    f.write(f"Precision: {precision:.6f}\n")
    f.write(f"Recall   : {recall:.6f}\n")
    f.write(f"F1-score : {f1:.6f}\n\n")

    f.write("="*60 + "\n")
    f.write("Classification Report\n")
    f.write("="*60 + "\n\n")

    f.write(report)

print("Classification report salvo com sucesso.")

cm = confusion_matrix(y_true,y_pred)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['NORMAL','PNEUMONIA'],
    yticklabels=['NORMAL','PNEUMONIA']
)

plt.xlabel('Predito')
plt.ylabel('Real')


plt.savefig(
    "/content/drive/MyDrive/pneumonia/Experimento_3/matriz_confusao_BaseLine.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(train_losses,label='Train')
plt.plot(val_losses,label='Validation')

plt.xlabel('Epoch')
plt.ylabel('Loss')

plt.legend()


plt.savefig(
    "/content/drive/MyDrive/pneumonia/Experimento_3/loss_curve_BaseLine.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(train_accs,label='Train')
plt.plot(val_accs,label='Validation')

plt.xlabel('Epoch')
plt.ylabel('Accuracy')

plt.legend()

plt.savefig(
    "/content/drive/MyDrive/pneumonia/Experimento_3/accuracy_curve_BaseLine.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()