# -*- coding: utf-8 -*-
"""Baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E-Q-pCHZ6Z3_ReN7wgmpqDiPZ07dyJvv
"""

import os
import copy
import zipfile
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

SEED = 42

torch.manual_seed(SEED)
np.random.seed(SEED)

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print(device)

from google.colab import files

files.upload()

!mkdir ~/.kaggle

!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d paultimothymooney/chest-xray-pneumonia

!unzip -q chest-xray-pneumonia.zip

print(os.listdir('/content/chest_xray'))

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

dataset = datasets.ImageFolder(
    root='/content/chest_xray/train',
    transform=transform
)

test_dataset = datasets.ImageFolder(
    root='/content/chest_xray/test',
    transform=transform
)

print(dataset.classes)

#Divisão Treino e Validação

train_size = int(0.8*len(dataset))
val_size = len(dataset)-train_size

train_dataset, val_dataset = random_split(
    dataset,
    [train_size,val_size],
    generator=torch.Generator().manual_seed(SEED)
)

#DataLoaders

BATCH_SIZE = 64

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

#Arquitetura CNN Baseline

class PneumoniaCNN(nn.Module):

    def __init__(self):

        super().__init__()

        self.features = nn.Sequential(

            nn.Conv2d(3,32,3,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(32,64,3,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(64,128,3,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),

            nn.Conv2d(128,256,3,padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2)

        )

        self.classifier = nn.Sequential(

            nn.Flatten(),

            nn.Linear(256*14*14,512),
            nn.ReLU(),

            nn.Dropout(0.5),

            nn.Linear(512,128),
            nn.ReLU(),

            nn.Linear(128,2)

        )

    def forward(self,x):

        x = self.features(x)
        x = self.classifier(x)

        return x

#Criando o modelo

model = PneumoniaCNN().to(device)

#Função de Perda

criterion = nn.CrossEntropyLoss()

#Otimizador - ADAM

optimizer = optim.Adam(
    model.parameters(),
    lr=0.001
)

#Épocas

NUM_EPOCHS = 30

from google.colab import drive

drive.mount('/content/drive')

import os

SAVE_DIR = "/content/drive/MyDrive/pneumonia/Experimento_1"

os.makedirs(SAVE_DIR, exist_ok=True)

import copy

best_val_loss = float('inf')
patience = 5
counter = 0

best_model_wts = copy.deepcopy(model.state_dict())

start_epoch = 0
start_epoch = 0

#Armazenar as métricas nas variáveis

train_losses = []
val_losses = []

train_accs = []
val_accs = []

checkpoint_path = os.path.join(SAVE_DIR, "checkpoint.pth")

if os.path.exists(checkpoint_path):

    checkpoint = torch.load(
        checkpoint_path,
        map_location=device
    )

    #Salvando o Histórico
    train_losses = checkpoint.get('train_losses', [])
    val_losses = checkpoint.get('val_losses', [])

    train_accs = checkpoint.get('train_accs', [])
    val_accs = checkpoint.get('val_accs', [])

    model.load_state_dict(
    checkpoint['model_state_dict']
    )



    optimizer.load_state_dict(
        checkpoint['optimizer_state_dict']
    )

    start_epoch = checkpoint['epoch'] + 1

    best_val_loss = checkpoint['best_val_loss']

    print(f"Treinamento retomado da época {start_epoch}")

else:

    print("Iniciando treinamento do zero")

# TREINAMENTO

NUM_EPOCHS = 30

for epoch in range(start_epoch, NUM_EPOCHS):





    model.train()

    running_loss = 0
    correct = 0
    total = 0

    for images, labels in train_loader:

        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        running_loss += loss.item()

        _, predicted = outputs.max(1)

        total += labels.size(0)

        correct += predicted.eq(labels).sum().item()

    train_loss = running_loss / len(train_loader)
    train_acc = correct / total

    train_losses.append(train_loss)
    train_accs.append(train_acc)

    #############################
    # VALIDAÇÃO
    #############################

    model.eval()

    running_loss = 0
    correct = 0
    total = 0

    with torch.no_grad():

        for images, labels in val_loader:

            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)

            loss = criterion(outputs, labels)

            running_loss += loss.item()

            _, predicted = outputs.max(1)

            total += labels.size(0)

            correct += predicted.eq(labels).sum().item()

    val_loss = running_loss / len(val_loader)
    val_acc = correct / total

    val_losses.append(val_loss)
    val_accs.append(val_acc)

    print(
        f'Epoch [{epoch+1}/{NUM_EPOCHS}] | '
        f'Train Loss={train_loss:.4f} | '
        f'Val Loss={val_loss:.4f} | '
        f'Train Acc={train_acc:.4f} | '
        f'Val Acc={val_acc:.4f}'
    )

    ###################################
    # SALVAR CHECKPOINT
    ###################################

    checkpoint = {

    'epoch': epoch,

    'model_state_dict': model.state_dict(),

    'optimizer_state_dict': optimizer.state_dict(),

    'best_val_loss': best_val_loss,

    'train_losses': train_losses,

    'val_losses': val_losses,

    'train_accs': train_accs,

    'val_accs': val_accs

}


    torch.save(
        checkpoint,
        os.path.join(
            SAVE_DIR,
            "checkpoint.pth"
        )
    )

    ###################################
    # MELHOR MODELO
    ###################################

    if val_loss < best_val_loss:

        best_val_loss = val_loss

        best_model_wts = copy.deepcopy(
            model.state_dict()
        )

        torch.save(
            model.state_dict(),
            os.path.join(
                SAVE_DIR,
                "best_model.pth"
            )
        )
        model = PneumoniaCNN().to(device)

        model.load_state_dict(
            torch.load(
                os.path.join(
                    SAVE_DIR,
                    "best_model.pth"
                ),
                map_location=device
            )
        )

        model.eval()

        counter = 0

        print(
            f"Melhor modelo salvo! "
            f"Val Loss = {val_loss:.4f}"
        )

    else:

        counter += 1

        print(
            f"Sem melhora ({counter}/{patience})"
        )

        if counter >= patience:

            print("Early Stopping")

            break

#Restaurando o melhor modelo
model.load_state_dict(
    torch.load(
        os.path.join(
            SAVE_DIR,
            "best_model.pth"
        ),
        map_location=device
    )
)

#Avalindo o conjunto de testes

model.eval()

y_true = []
y_pred = []

with torch.no_grad():

    for images, labels in test_loader:

        images = images.to(device)

        outputs = model(images)

        _, predicted = outputs.max(1)

        y_true.extend(labels.numpy())
        y_pred.extend(predicted.cpu().numpy())

acc = accuracy_score(y_true,y_pred)
precision = precision_score(y_true,y_pred)
recall = recall_score(y_true,y_pred)
f1 = f1_score(y_true,y_pred)

print("Accuracy :",acc)
print("Precision:",precision)
print("Recall   :",recall)
print("F1-score :",f1)

with open("/content/drive/MyDrive/pneumonia/Experimento_1/metricas_BaseLine.txt", "w") as f:

    f.write(f"Accuracy : {acc:.6f}\n")
    f.write(f"Precision: {precision:.6f}\n")
    f.write(f"Recall   : {recall:.6f}\n")
    f.write(f"F1-score : {f1:.6f}\n")

print("Métricas salvas em metricas.txt")

import pandas as pd

resultados = pd.DataFrame({

    "Modelo": ["CNN Baseline"],

    "Accuracy": [acc],

    "Precision": [precision],

    "Recall": [recall],

    "F1-score": [f1]

})

resultados.to_csv(
    os.path.join(SAVE_DIR, "metricas.csv"),
    index=False
)

print("Métricas salvas em metricas.csv")

report = classification_report(
    y_true,
    y_pred,
    target_names=['NORMAL', 'PNEUMONIA']
)

print(report)

with open(
    "/content/drive/MyDrive/pneumonia/Experimento_1/classification_report_BaseLine.txt",
    "w"
) as f:

    f.write("CNN Baseline\n")
    f.write("="*60 + "\n\n")

    f.write(f"Accuracy : {acc:.6f}\n")
    f.write(f"Precision: {precision:.6f}\n")
    f.write(f"Recall   : {recall:.6f}\n")
    f.write(f"F1-score : {f1:.6f}\n\n")

    f.write("="*60 + "\n")
    f.write("Classification Report\n")
    f.write("="*60 + "\n\n")

    f.write(report)

print("Classification report salvo com sucesso.")

cm = confusion_matrix(y_true,y_pred)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['NORMAL','PNEUMONIA'],
    yticklabels=['NORMAL','PNEUMONIA']
)

plt.xlabel('Predito')
plt.ylabel('Real')


plt.savefig(
    "/content/drive/MyDrive/pneumonia/Experimento_1/matriz_confusao_BaseLine.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(train_losses,label='Train')
plt.plot(val_losses,label='Validation')

plt.xlabel('Epoch')
plt.ylabel('Loss')

plt.legend()


plt.savefig(
    "/content/drive/MyDrive/pneumonia/Experimento_1/loss_curve_BaseLine.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

plt.figure(figsize=(8,5))

plt.plot(train_accs,label='Train')
plt.plot(val_accs,label='Validation')

plt.xlabel('Epoch')
plt.ylabel('Accuracy')

plt.legend()

plt.savefig(
    "/content/drive/MyDrive/pneumonia/Experimento_1/accuracy_curve_BaseLine.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()